import io
import os
from datetime import datetime, timezone

import boto3
import openpyxl
import yaml
from dotenv import load_dotenv

load_dotenv()

CF_R2_ACCESS_KEY = os.getenv("CF_R2_ACCESS_KEY_ID")
CF_R2_SECRET_KEY = os.getenv("CF_R2_SECRET_ACCESS_KEY")
CF_R2_ENDPOINT_URL = os.getenv("CF_R2_ENDPOINT_URL")
BUCKET_NAME = os.getenv("CF_R2_BUCKET_NAME", "")

CLEAN_ENDPOINT = ""
if CF_R2_ENDPOINT_URL:
    CLEAN_ENDPOINT = CF_R2_ENDPOINT_URL.rstrip("/").removesuffix("/" + BUCKET_NAME)

STATS_KEY = "DKSA/monitor/monitor_stats.yml"
MAX_OBSERVED_DATES = 30

# Categories where excel/ holds many files (one per manufacturer) instead of
# one combined category file -- tracked differently in monitor_stats.yml.
MULTI_FILE_CATEGORIES = {"Vehicles"}

HEADER = (
    "# Auto-generated by monitor/build_monitor_stats.py\n"
    "# Stored in Cloudflare R2 -- do not add to the repo.\n"
    "# Re-run the daily monitor workflow to refresh.\n\n"
)


def get_r2_client():
    if not (CF_R2_ACCESS_KEY and CF_R2_SECRET_KEY and CLEAN_ENDPOINT):
        raise RuntimeError("R2 environment variables are missing.")
    return boto3.client(
        "s3",
        endpoint_url=CLEAN_ENDPOINT,
        aws_access_key_id=CF_R2_ACCESS_KEY,
        aws_secret_access_key=CF_R2_SECRET_KEY,
        region_name="auto",
    )


def load_existing_stats(client) -> dict:
    try:
        resp = client.get_object(Bucket=BUCKET_NAME, Key=STATS_KEY)
        data = yaml.safe_load(resp["Body"].read().decode("utf-8")) or {}
        print(f"Loaded existing stats from r2://{BUCKET_NAME}/{STATS_KEY}")
        return data
    except client.exceptions.NoSuchKey:
        print("No existing monitor_stats.yml -- starting fresh.")
        return {}
    except Exception as e:
        print(f"Could not load existing stats: {e} -- starting fresh.")
        return {}


def save_stats(client, stats: dict) -> None:
    body = (HEADER + yaml.dump(
        stats, allow_unicode=True, default_flow_style=False, sort_keys=True
    )).encode("utf-8")
    client.put_object(Bucket=BUCKET_NAME, Key=STATS_KEY, Body=body, ContentType="text/yaml")
    print(f"Saved -> r2://{BUCKET_NAME}/{STATS_KEY}")


def list_today_categories(client, dt: datetime) -> list[str]:
    prefix = f"DKSA/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/"
    paginator = client.get_paginator("list_objects_v2")
    categories = []
    for page in paginator.paginate(Bucket=BUCKET_NAME, Prefix=prefix, Delimiter="/"):
        for cp in page.get("CommonPrefixes", []):
            name = cp["Prefix"][len(prefix):].rstrip("/")
            if name:
                categories.append(name)
    return sorted(categories)


def find_main_excel_key(client, dt: datetime, category: str) -> str | None:
    """Single-file categories: excel/{slug}.xlsx."""
    prefix = f"DKSA/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/{category}/excel/"
    resp = client.list_objects_v2(Bucket=BUCKET_NAME, Prefix=prefix, Delimiter="/")
    for obj in resp.get("Contents", []):
        key = obj["Key"]
        if key.endswith(".xlsx"):
            return key
    return None


def find_all_excel_keys(client, dt: datetime, category: str) -> list[str]:
    """Multi-file categories (e.g. Vehicles): every {make}.xlsx under excel/."""
    prefix = f"DKSA/year={dt.year}/month={dt.strftime('%m')}/day={dt.strftime('%d')}/{category}/excel/"
    resp = client.list_objects_v2(Bucket=BUCKET_NAME, Prefix=prefix, Delimiter="/")
    return sorted(
        obj["Key"] for obj in resp.get("Contents", [])
        if obj["Key"].endswith(".xlsx")
    )


def inspect_excel(raw: bytes) -> list[dict]:
    """Returns [{name, row_count, columns: [str]}] per sheet."""
    sheets = []
    wb = openpyxl.load_workbook(io.BytesIO(raw), read_only=True, data_only=True)
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows_iter = ws.iter_rows(values_only=True)
        header_row = next(rows_iter, None)
        headers = [str(c) for c in header_row if c is not None] if header_row else []
        row_count = sum(1 for _ in rows_iter)
        sheets.append({"name": sheet_name, "row_count": row_count, "columns": headers})
    wb.close()
    return sheets


def accumulate_single_file(stats: dict, category: str, size_bytes: int, sheets: list[dict], date_str: str) -> None:
    entry = stats.setdefault(category, {
        "file_size_kb": {"min": None, "max": None, "last": None},
        "observed_dates": [],
        "sheets": {},
    })

    if date_str not in entry["observed_dates"]:
        entry["observed_dates"].append(date_str)
        entry["observed_dates"] = sorted(entry["observed_dates"])[-MAX_OBSERVED_DATES:]

    kb = round(size_bytes / 1024, 1)
    fs = entry["file_size_kb"]
    fs["last"] = kb
    fs["min"] = min(kb, fs["min"]) if fs["min"] is not None else kb
    fs["max"] = max(kb, fs["max"]) if fs["max"] is not None else kb

    for sheet in sheets:
        sname = sheet["name"]
        se = entry["sheets"].setdefault(sname, {
            "columns": [],
            "row_count": {"min": None, "max": None, "last": None},
        })
        rc = sheet["row_count"]
        se["row_count"]["last"] = rc
        se["row_count"]["min"] = min(rc, se["row_count"]["min"]) if se["row_count"]["min"] is not None else rc
        se["row_count"]["max"] = max(rc, se["row_count"]["max"]) if se["row_count"]["max"] is not None else rc
        new_cols = [c for c in sheet["columns"] if c not in se["columns"]]
        se["columns"].extend(new_cols)


def accumulate_multi_file(client, stats: dict, category: str, excel_keys: list[str], date_str: str) -> None:
    """
    For categories like Vehicles: each {make}.xlsx becomes one logical
    "sheet" entry -- row_count = sum of rows across all its model sheets,
    columns = columns of its first sheet. file_size_kb is the sum of all
    make files' sizes for the day.
    """
    entry = stats.setdefault(category, {
        "file_size_kb": {"min": None, "max": None, "last": None},
        "observed_dates": [],
        "sheets": {},
    })

    if date_str not in entry["observed_dates"]:
        entry["observed_dates"].append(date_str)
        entry["observed_dates"] = sorted(entry["observed_dates"])[-MAX_OBSERVED_DATES:]

    total_size_bytes = 0

    for key in excel_keys:
        make_name = os.path.splitext(os.path.basename(key))[0]

        obj = client.get_object(Bucket=BUCKET_NAME, Key=key)
        raw = obj["Body"].read()
        total_size_bytes += len(raw)

        sheets = inspect_excel(raw)
        if not sheets:
            continue

        row_count = sum(s["row_count"] for s in sheets)
        columns = sheets[0]["columns"]

        se = entry["sheets"].setdefault(make_name, {
            "columns": [],
            "row_count": {"min": None, "max": None, "last": None},
        })
        se["row_count"]["last"] = row_count
        se["row_count"]["min"] = min(row_count, se["row_count"]["min"]) if se["row_count"]["min"] is not None else row_count
        se["row_count"]["max"] = max(row_count, se["row_count"]["max"]) if se["row_count"]["max"] is not None else row_count
        new_cols = [c for c in columns if c not in se["columns"]]
        se["columns"].extend(new_cols)

    kb = round(total_size_bytes / 1024, 1)
    fs = entry["file_size_kb"]
    fs["last"] = kb
    fs["min"] = min(kb, fs["min"]) if fs["min"] is not None else kb
    fs["max"] = max(kb, fs["max"]) if fs["max"] is not None else kb


def run():
    client = get_r2_client()
    dt = datetime.now(timezone.utc)
    date_str = dt.strftime("%Y-%m-%d")

    stats = load_existing_stats(client)
    categories = list_today_categories(client, dt)
    print(f"Categories found for {date_str}: {categories}")

    for category in categories:
        if category in MULTI_FILE_CATEGORIES:
            excel_keys = find_all_excel_keys(client, dt, category)
            if not excel_keys:
                print(f"  {category}: no excel files found -- skipping.")
                continue
            accumulate_multi_file(client, stats, category, excel_keys, date_str)