folder: DKSA
site_id: dubizzle-SA
display_name: Dubizzle Saudi Arabia
website: dubizzle.sa/en/
country: Saudi Arabia
github_username: Dev545989
repo: SD
run_place: github
uses_proxy: false
r2_prefix: DKSA
scrapers: 11
schedule: daily
data_format: xlsx
workflows:
  - "DKSA"
